#!bin/bash
source sourceme.sh
declare -x NOVAS_HOME="/compas/opt/synopsys/verdi/R-2020.12"
declare -x PATH="$PATH:/compas/opt/altera/16.1/hld/bin:/compas/opt/altera/16.1/quartus/bin:/compas/opt/modelsim10/modeltech/bin:/compas/opt/Bluespec-2014.05.C/lib/../bin:/compas/opt/synopsys/verdi/R-2020.12/bin:/compas/opt/synopsys/vcs/Q-2020.03-SP2-1/bin:/compas/opt/synopsys/vcs/Q-2020.03-SP2-1/bin:/compas/opt/synopsys/I-2014.03/bin:/compas/opt/MATLAB/R2012b/bin:/usr/lib/lightdm/lightdm:/compas/opt/Xilinx/Model_Composer/2020.1/bin:/compas/opt/Xilinx/Vivado/2020.1/bin:/compas/opt/Xilinx/Vitis/2020.1/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/microblaze/lin/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/arm/lin/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/microblaze/linux_toolchain/lin64_le/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/aarch64/lin/aarch64-linux/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/aarch64/lin/aarch64-none/bin:/compas/opt/Xilinx/Vitis/2020.1/gnu/armr5/lin/gcc-arm-none-eabi/bin:/compas/opt/Xilinx/Vitis/2020.1/tps/lnx64/cmake-3.3.2/bin:/compas/opt/Xilinx/Vitis/2020.1/cardano/bin:/compas/opt/Xilinx/DocNav:/compas/opt/slurm/bin:/compas/opt/slurm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x XILINXD_LICENSE_FILE="2101@license.ece.stonybrook.edu"
declare -x XILINX_VITIS="/compas/opt/Xilinx/Vitis/2020.1"
declare -x XILINX_VIVADO="/compas/opt/Xilinx/Vivado/2020.1"
declare -x ALTERAOCLSDKROOT="/compas/opt/altera/16.1/hld"
declare -x ALTERAROOT="/compas/opt/altera/16.1"
declare -x AOCL_BOARD_PACKAGE_ROOT="/compas/opt/altera/16.1/hld/board/terasic/de5net"
declare -x BLUESPECDIR="/compas/opt/Bluespec-2014.05.C/lib"
declare -x BLUESPEC_HOME="/compas/opt/Bluespec-2014.05.C"
declare -x COLORTERM="truecolor"
declare -x QUARTUS_64BIT="1"
declare -x VCS_ARCH_OVERRIDE="linux"
declare -x VCS_HOME="/compas/opt/synopsys/vcs/Q-2020.03-SP2-1"
declare -x SYNOPSYS_SIM="/compas/opt/synopsys/vcs/Q-2020.03-SP2-1"
declare -x SYNPLIFYPRO_LICENSE_TYPE="synplifypremierdp"
declare -x LD_LIBRARY_PATH="/compas/opt/altera/16.1/hld/board/terasic/de5net/linux64/lib:/compas/opt/altera/16.1/hld/host/linux64/lib:/compas/opt/synopsys/verdi/R-2020.12/share/PLI/lib/LINUX64:/lib:/usr/lib:.:/compas/opt/synopsys/vcs/Q-2020.03-SP2-1/linux/lib:/compas/opt/synopsys/vcs/Q-2020.03-SP2-1/"
declare -x LM_LICENSE_FILE=":27020@license4.ece.stonybrook.edu:5000@license4.ece.stonybrook.edu:27005@breweryhill:1717@license.ece.stonybrook.edu:5500@license4.ece.stonybrook.edu:2101@license0.ece.stonybrook.edu"
declare -x QSYS_ROOTDIR="/compas/opt/altera/16.1/quartus/sopc_builder/bin"
declare -x QUARTUS_64BIT="1"
declare -x SHELL="/bin/bash"
declare -x SHLVL="3"
declare -x SPECMAN_HOME="/compas/opt/synopsys/vcs/Q-2020.03-SP2-1"
declare -x SPECMAN_LICENSE_FILE="4999@license.ece.stonybrook.edu"
declare -x SPECMAN_VCSMX_VHDL_ADAPTER="/compas/opt/synopsys/vcs/Q-2020.03-SP2-1/linux/lib/libvhdl_sn_adapter.so"